#################################################
# Variables
#################################################
variables:
  - name: backendGcsBucket
    value: tf-state62626

  - name: backendGcsPrefix
    value: terraform/state

  - name: workingDirectory
    value: ./application

#################################################
# Triggers
#################################################
pr: none
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - application

#################################################
# Parameters
#################################################
parameters:
  - name: imageTag
    type: string
    default: '247904'

pool:
  name: Default

stages:
  - stage: DOWNLOAD_AND_PUBLISH
    displayName: Obtain image from source and publish
    jobs:
      - job: PUBLISH_IMAGE
        displayName: Publish image to GAR
        steps:
          - script: docker pull dfranciswoolies/ciarecruitment-bestapiever:${{ parameters.imageTag }}
            displayName: Download image from Docker Hub
          - script: |
              docker tag dfranciswoolies/ciarecruitment-bestapiever:${{ parameters.imageTag }} australia-southeast1-docker.pkg.dev/wooliesx-interview/wooliesx-interview-repo/weather-forecast-api:${{ parameters.imageTag }}
            displayName: Tag downloaded image to prepare for GAR
          - script: |
              docker login -u _json_key --password-stdin https://australia-southeast1-docker.pkg.dev < wooliesx-interview-pipeline-gar.json
            displayName: Login to GAR

  # - stage: APPLY_AND_PROVISION
  #   displayName: Run Terraform Apply and provision resources
  #   dependsOn: DOWNLOAD_AND_PUBLISH
  #   jobs:
  #     - job: TERRAFORM_APPLY
  #       displayName: Apply Terraform resources
  #       steps:
  #         - download: current
  #           artifact: drop
  #         - task: TerraformInstaller@0
  #           displayName: Install latest Terraform version
  #           inputs:
  #             terraformVersion: latest
  #         - task: TerraformCLI@0
  #           displayName: Run Terraform Init
  #           inputs:
  #             command: init
  #             workingDirectory: $(workingDirectory)
  #             backendType: gcs
  #             # Google Credentials (i.e. for service account) in JSON file format in Azure DevOps Secure Files
  #             backendGcsCredentials: wooliesx-interview-tf-state.json
  #             # GCS bucket name
  #             backendGcsBucket: $(backendGcsBucket)
  #             # GCS Bucket path to state file
  #             backendGcsPrefix: $(backendGcsPrefix)
  #         - task: TerraformCLI@0
  #           displayName: Run Terraform Apply
  #           inputs:
  #             command: apply
  #             workingDirectory: $(workingDirectory)
  #             # Google Credentials (i.e. for service account) in JSON file format in Azure DevOps Secure Files
  #             providerGoogleCredentials: wooliesx-interview-tf.json
  #             # The default project name where resources are managed. Defining project on a resource takes precedence over this.
  #             providerGoogleProject: wooliesx-interview
  #             # The default region where resources are managed. Defining region on a resource takes precedence over this.
  #             providerGoogleRegion: australia-southeast1
  #             commandOptions: "-auto-approve"
